---@diagnostic disable: undefined-global
local A = ValSpams

A.localeStrings = {
	enUS = {
		announce = "Announcements",
		announceDescription = "Broadcast alert messages to your current group channel.",
		classes = "Classes",
		classesDescription = "Choose which class spell lists are available under ValSpams.",
		classSpellsDescription = "Enable or disable tracked spells for this class.",
		noTrackedSpells = "No tracked spells are configured for this class yet.",
		debug = "Debug",
		debugDescription = "Enable extra local debug output while testing.",
		trackTrinkets = "Track trinkets",
		trackTrinketsDescription = "Announce on-use trinket activations from your equipped trinket slots.",
		categoryToggles = "Category filters",
		categoryTogglesDescription = "Enable or disable whole announcement categories before per-spell checks.",
		ccScope = "Crowd-control scope",
		ccScopeDescription = "Choose whether CC announcements follow only your casts or all tracked CC seen in combat.",
		ccScopeMine = "My CC only",
		ccScopeAllTracked = "All tracked CC",
		warningOffensive = "Offensives can be noisy in raid combat.",
		warningCrowdControl = "All tracked CC can be noisy when many players are controlling mobs.",
		warningTrinkets = "Trinket usage can be noisy if you rotate on-use items often.",
		warningInterruptElvUI = "Interrupt announcements are automatically disabled while ElvUI is installed.",
		channelMode = "Announcement Channel",
		channelModeDescription = "Choose whether announcements follow the default group priority or always use yell or say.",
		channelPriority = "Raid > Party > Yell",
		channelYellOnly = "Yell only",
		channelSayOnly = "Say only",
		announceMode = "Tracked Aura Announce Mode",
		announceModeDescription = "Choose how tracked aura announcements behave.",
		modeCastOnly = "Cast only",
		modeEnding = "Cast + ending",
		optionsSubtitle = "Configure which combat announcements this addon sends to party, raid, or local chat.",
		helpText = "Slash commands: /vs, /valspams, /vs announce, /vs debug",
		openedOptions = "Opened ValSpams options.",
		usage = "Usage: /vs, /valspams, /vs announce, /vs debug",
		categoryDefensive = "Defensive",
		categoryOffensive = "Offensive",
		categoryTaunt = "Taunt",
		categoryCrowdControl = "Crowd Control",
		categoryTrinket = "Trinket",
		categoryInterrupt = "Interrupt",
		categoryImportantTankOutcome = "Important Tank Outcome",
		categoryUtility = "Utility",
		outcomeMiss = "missed",
		outcomeDodge = "dodged",
		outcomeParry = "parried",
		outcomeResist = "resisted",
		outcomeImmune = "immune",
		outcomeBroken = "broke early",
		castMessage = "Activated: spell:link spell:duration!",
		castOnMessage = "spell:link cast on spell:target! spell:duration",
		castCrowdControlOnMessage = "spell:link cast on spell:target! spell:duration",
		castNoDurationOnMessage = "spell:link cast on spell:target!",
		castWhisperOnMessage = "spell:link cast on you! spell:duration",
		endedMessage = "spell:link fading.",
		endedOnMessage = "spell:link faded from spell:target.",
		missMessage = "spell:link spell:missType!",
		missOnMessage = "spell:link spell:missType!",
		breakMessage = "spell:link faded.",
		breakOnMessage = "spell:link faded from spell:target.",
		dispelMessage = "Dispelled spell:extraLink!",
		dispelOnMessage = "Dispelled spell:extraLink off spell:target!",
		tankMissMessage = "WARNING spell:link spell:missType!",
		interruptMessage = "spell:link interrupted!",
		interruptOnMessage = "spell:target's spell:link interrupted!",
	},
	koKR = {
		announce = "알림",
		announceDescription = "현재 파티 또는 공격대 채널로 경고 메시지를 보냅니다.",
		classes = "직업",
		classesDescription = "ValSpams 아래에서 직업별 주문 추적 목록을 설정합니다.",
		classSpellsDescription = "이 직업에서 추적할 주문을 켜거나 끕니다.",
		noTrackedSpells = "아직 이 직업에 설정된 추적 주문이 없습니다.",
		debug = "디버그",
		debugDescription = "테스트 중 추가 디버그 메시지를 표시합니다.",
		trackTrinkets = "장신구 추적",
		trackTrinketsDescription = "착용한 장신구 칸의 사용 효과를 알립니다.",
		categoryToggles = "카테고리 필터",
		categoryTogglesDescription = "개별 주문 체크보다 먼저 전체 카테고리를 켜거나 끕니다.",
		ccScope = "군중 제어 범위",
		ccScopeDescription = "내 CC만 볼지, 전투 중 보이는 추적 CC 전체를 볼지 선택합니다.",
		ccScopeMine = "내 CC만",
		ccScopeAllTracked = "추적 CC 전체",
		warningOffensive = "공격 지원기 알림은 공격대 전투에서 많아질 수 있습니다.",
		warningCrowdControl = "여러 명이 CC를 쓰면 전체 추적 CC 알림이 많아질 수 있습니다.",
		warningTrinkets = "사용 장신구를 자주 돌리면 알림이 많아질 수 있습니다.",
		warningInterruptElvUI = "ElvUI가 설치되어 있으면 차단 알림은 자동으로 비활성화됩니다.",
		channelMode = "알림 채널",
		channelModeDescription = "기본 우선순위를 사용할지 항상 외치기 또는 일반 대화를 사용할지 선택합니다.",
		channelPriority = "공격대 > 파티 > 외치기",
		channelYellOnly = "외치기 전용",
		channelSayOnly = "일반 대화 전용",
		announceMode = "추적 효과 알림 방식",
		announceModeDescription = "추적 중인 효과의 알림 방식을 선택합니다.",
		modeCastOnly = "시전만 알림",
		modeEnding = "시전 + 종료 알림",
		optionsSubtitle = "이 애드온이 파티, 공격대 또는 일반 채팅에 보낼 "..
			"전투 알림을 설정합니다.",
		helpText = "슬래시 명령어: /vs, /valspams, /vs announce, /vs debug",
		openedOptions = "ValSpams 설정을 열었습니다.",
		usage = "사용법: /vs, /valspams, /vs announce, /vs debug",
		categoryDefensive = "생존기",
		categoryOffensive = "공격기",
		categoryTaunt = "도발",
		categoryCrowdControl = "군중 제어",
		categoryTrinket = "장신구",
		categoryInterrupt = "차단",
		categoryImportantTankOutcome = "중요 탱킹 결과",
		categoryUtility = "유틸리티",
		outcomeMiss = "빗나갔습니다",
		outcomeDodge = "회피되었습니다",
		outcomeParry = "막혔습니다",
		outcomeResist = "저항되었습니다",
		outcomeImmune = "면역되었습니다",
		outcomeBroken = "일찍 해제되었습니다",
		castMessage = "시전: spell:link spell:duration!",
		castOnMessage = "spell:target에게 spell:link 시전됩니다! spell:duration",
		castCrowdControlOnMessage = "spell:target에 spell:link! spell:duration",
		castNoDurationOnMessage = "spell:target에게 spell:link 시전됩니다!",
		castWhisperOnMessage = "spell:link 당신에게 시전됩니다! spell:duration",
		endedMessage = "spell:link 사라집니다.",
		endedOnMessage = "spell:target에게서 spell:link 사라집니다.",
		missMessage = "spell:link 실패!",
		missOnMessage = "spell:link 실패!",
		breakMessage = "spell:link 사라집니다.",
		breakOnMessage = "spell:target에게서 spell:link 사라집니다.",
		dispelMessage = "spell:extraLink 해제됩니다!",
		dispelOnMessage = "spell:target에게서 spell:extraLink 해제됩니다!",
		tankMissMessage = "경고: spell:link spell:missType!",
		interruptMessage = "spell:link 차단됨!",
		interruptOnMessage = "spell:target의 spell:link 차단됩니다!",
	}
}

A.L = A.localeStrings[A.locale] or A.localeStrings.enUS

A.optionLabels = {
	announce = A.L.announce,
	debug = A.L.debug,
	trackTrinkets = A.L.trackTrinkets,
}

A.optionDescriptions = {
	announce = A.L.announceDescription,
	debug = A.L.debugDescription,
	trackTrinkets = A.L.trackTrinketsDescription,
}

A.announceModeLabels = {
	cast_only = A.L.modeCastOnly,
	ending = A.L.modeEnding
}

A.channelModeLabels = {
	priority = A.L.channelPriority,
	yell_only = A.L.channelYellOnly,
	say_only = A.L.channelSayOnly
}

A.ccScopeLabels = {
	mine = A.L.ccScopeMine,
	all_tracked = A.L.ccScopeAllTracked
}

A.categoryLabels = {
	defensive = A.L.categoryDefensive,
	offensive = A.L.categoryOffensive,
	taunt = A.L.categoryTaunt,
	crowd_control = A.L.categoryCrowdControl,
	trinket = A.L.categoryTrinket,
	interrupt = A.L.categoryInterrupt,
	important_tank_outcome = A.L.categoryImportantTankOutcome,
	utility = A.L.categoryUtility,
}